version: '3'
services:
  jupyter-labn:
    build: ./docker/jupyter
    #image: tensorflow/tensorflow:latest-gpu-py3-jupyter
    shm_size: '1gb'
    ports:
      - 6006:6006
      - 6007:6007
      - 9999:8888
      - 7022:7022
    volumes:
      - ./:/home/user/notebooks
      - ./data-csv:/opt/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
  vertica:
    #image: jbfavre/vertica:9.2.0-6_debian-8
    image: akodd/vertica:9.2.0-6_ubuntu-16.04
    #network_mode: "host"
    ports:
      - 5433:5433
      - 5450:5450
    volumes:
      - ./data-db/vertica:/home/dbadmin/docker
      - ./data-csv:/opt/data:ro
      - ./:/home/dbadmin/gse-loan:ro
  rstudio:
    #image: rocker/verse:3.5.3
    build: ./docker/rstudio-verse-mod
    ports:
      - 8787:8787
    volumes:
      - ./:/home/rstudio
      - ./data/data-csv:/opt/data
    environment:
      - PASSWORD=gse-loan
