copy fnm_prf (
   loan_id,
   rpt_period_str filler varchar(10),
   rpt_period as to_date(rpt_period_str, 'MM/DD/YYYY'),
   servicer_name,
   int_rate,
   current_upb,
   age,
   months_to_maturity,
   months_to_maturity_adj,
   maturity_date_str filler varchar(7),
   maturity_date as to_date('01/' || maturity_date_str, 'DD/MM/YYYY'),
   msa,
   del,
   modification_flag,
   zero_bal_code,
   zero_bal_date_str filler varchar(7),
   zero_bal_date as to_date('01/' || zero_bal_date_str, 'DD/MM/YYYY'),
   lpi_date_str filler varchar(10),
   lpi_date as to_date(lpi_date_str, 'MM/DD/YYYY'),
   foreclosure_date_str filler varchar(10),
   foreclosure_date as to_date(foreclosure_date_str, 'MM/DD/YYYY'),
   disposition_date_str filler varchar(10),
   disposition_date as to_date(disposition_date_str, 'MM/DD/YYYY'),
   foreclosure_cost,
   ppp_cost,
   recovery_cost,
   holding_cost,
   tax_cost,
   net_sales,
   credit_enh_procs,
   repurchase_procs,
   other_procs,
   non_int_upb,
   prin_forg_upb,
   make_whole_ind,
   forclosure_prin_write_off,
   servicing_activity_ind
)
from 'PERF_CURRENT' delimiter '|' null '' enforcelength trailing nullcols abort on error direct;
